<Project>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <PackageVersion Include="OpenCvSharp4" Version="4.10.0.20240616" />
    <PackageVersion Include="OpenCvSharp4.runtime.win" Version="4.10.0.20240616" />
    <PackageVersion Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>
</Project>
