<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\StaticSignatureVerification.Core\StaticSignatureVerification.Core.csproj" />
    <ProjectReference Include="..\StaticSignatureVerification.PdfRendering\StaticSignatureVerification.PdfRendering.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
