<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\StaticSignatureVerification.Core\StaticSignatureVerification.Core.csproj" />
    <ProjectReference Include="..\StaticSignatureVerification.PdfRendering\StaticSignatureVerification.PdfRendering.csproj" />
    <Compile Include="..\StaticSignatureVerification.TotalAgilityWrapper\SignatureVerificationWrapper.cs" Link="SignatureVerificationWrapper.cs" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
